### ISSUE TITLE
希望本项目可以继续完善下，像 ant-design-pro 这样开箱即用

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/antd-mobile5-template#3]
希望本项目可以继续完善下，像 ant-design-pro 这样开箱即用

**Comment by xiaohuoni** [comment]
我个人有计划，正在定类型。pro 直接中后台项目，很符合 antd 的设计。
mobile@5 感觉是移动端都要包含，我不确定什么类型的适用。
你有建议吗？

**Comment by xiaohuoni** [comment]
安排 👍  https://github.com/ant-design/antd-mobile-pro
